#!/usr/bin/env bash
# Interactive .env generator for Semivra POS production deployment.
# Generates strong secrets, prompts for the rest, writes server/.env.
#
# Usage: bash scripts/setup-env.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/server/.env"

echo ""
echo "  Semivra POS — Production .env Generator"
echo "  ========================================"
echo ""

if [[ -f "$ENV_FILE" ]]; then
  read -r -p "  $ENV_FILE already exists. Overwrite? [y/N] " confirm
  [[ "${confirm,,}" == "y" ]] || { echo "  Aborted."; exit 1; }
fi

# Generate strong JWT secret (32 random bytes → 64 hex chars)
JWT_SECRET="$(openssl rand -hex 32 2>/dev/null || head -c32 /dev/urandom | xxd -p | tr -d '\n')"
echo "  ✓ Generated JWT_SECRET (64 hex chars)"

# Generate a strong default admin password
ADMIN_PASS="$(openssl rand -base64 16 2>/dev/null | tr -d '=+/' | cut -c1-16 || echo 'ChangeMe@2026!')"
echo "  ✓ Generated ADMIN_PASS (16 chars — record this!)"
echo "    ► ADMIN_PASS = $ADMIN_PASS"
echo ""

read -r -p "  MongoDB URI (mongodb+srv://...): " MONGO_URI
[[ -z "$MONGO_URI" ]] && { echo "  ERROR: MONGO_URI required."; exit 1; }

read -r -p "  Frontend origin (e.g. https://pos.your-domain.com): " ORIGIN
[[ -z "$ORIGIN" ]] && ORIGIN="http://localhost:3000"

read -r -p "  Server port [5002]: " PORT
PORT="${PORT:-5002}"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
NODE_ENV=production
PORT=$PORT
MONGO_URI=$MONGO_URI
JWT_SECRET=$JWT_SECRET
ALLOWED_ORIGINS=$ORIGIN
ADMIN_PASS=$ADMIN_PASS
LOG_LEVEL=info
EOF

chmod 600 "$ENV_FILE"
echo ""
echo "  ✓ Wrote $ENV_FILE (mode 600 — owner-readable only)"
echo ""
echo "  Next steps:"
echo "    1. docker compose up -d --build"
echo "    2. Login as 'Super Admin' with the password above"
echo "    3. Change the password immediately via Superadmin Panel"
echo "    4. Point uptime monitor at http://your-host:$PORT/health"
echo ""
